Add recent blog posts sidebar to the blog article page
slightlynerd/startupgraveyard.africa pull request #28
Opened 2024-05-01 18:59 UTC by tsomic

Closes #24 

I also removed the hacky footer logic on the blog page because it made adding the sidebar easier.
I get the last 4 blog posts and filter out the current post so there's always three blog posts on the right.

2024-05-02 12:40 UTC, slightlynerd requested changes

2024-05-02 12:40 UTC, slightlynerd commented on pages/blog/[id].vue
> +    display: flex;
@tsomic Since bootstrap is used in the project, use bootstrap classes (row, col-*) to achieve the same behavior.

2024-05-02 12:40 UTC, slightlynerd commented on pages/blog/[id].vue
> +      flex-direction: column;
@tsomic Same as previous comment

2024-05-02 12:40 UTC, slightlynerd commented on pages/blog/[id].vue
> +  .blog-recent {
@tsomic same as previous comment

2024-05-02 12:48 UTC, slightlynerd requested changes

2024-05-02 12:48 UTC, slightlynerd commented on pages/blog/[id].vue
> +      <div class="blog-sidebar">
@tsomic Check responsiveness of sidebar. If it doesn't look okay at a certain breakpoint, you can collapse the row into a column there: 

<img width="887" alt="Screenshot 2024-05-02 at 13 46 12" src="https://github.com/slightlynerd/startupgraveyard.africa/assets/19628361/5e3d9dc8-179a-48d9-9fe9-4a4b3518d191">

2024-05-02 13:43 UTC, tsomic commented on pages/blog/[id].vue
> +      <div class="blog-sidebar">
Done

2024-05-02 13:45 UTC, tsomic commented on pages/blog/[id].vue
> +    display: flex;
I tried doing that right now, but I couldn't get it to work in a way that satisfied me. It was never quite aligned the way I wanted it to be.
It also may be because I have no experience with Bootstrap, maybe you can give it a try

2024-05-02 14:19 UTC, slightlynerd commented on pages/blog/[id].vue
> +    display: flex;
@tsomic Check out the documentation https://getbootstrap.com/docs/5.3/layout/grid/

2024-05-03 10:56 UTC, KelvinGoboZap commented on pages/blog/[id].vue
> +  recentBlogPosts.value = recentBlogPosts.value.slice(0, 3);
@tsomic Is this line necessary? If so, why is it needed?

2024-05-03 11:09 UTC, slightlynerd requested changes

2024-05-03 11:09 UTC, slightlynerd commented on pages/blog/[id].vue
> +  recentBlogPosts.value = recentBlogPosts.value.slice(0, 3);
@tsomic add an if-condition to check `recentBlogPosts.value.length > 3` before this operation. 

```javascript
if (recentBlogPosts.value?.length > MAX_RECENT_POSTS) {
  recentBlogPosts.value = recentBlogPosts.value.slice(0, MAX_RECENT_POSTS);
}

2024-05-03 11:09 UTC, slightlynerd commented on pages/blog/[id].vue
> +const MIN_BLOG_POSTS = 4;
```suggestion
const MAX_RECENT_POSTS = 3;
const NO_OF_POSTS_TO_FETCH = 4;
```

2024-05-03 11:09 UTC, slightlynerd commented on pages/blog/[id].vue
> +    limit(MIN_BLOG_POSTS)
```suggestion
    limit(NO_OF_POSTS_TO_FETCH)
```

2024-05-03 11:39 UTC, slightlynerd approved these changes

2024-05-03 11:39 UTC, merged