Adds earch functionality to /blog
slightlynerd/startupgraveyard.africa pull request #29
Opened 2024-05-04 17:59 UTC by tsomic

Closes #25 

I did not take the pagination into account, but at the moment that is not properly implemented anyways.

2024-05-05 19:29 UTC, KelvinGoboZap requested changes

2024-05-05 19:29 UTC, KelvinGoboZap commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
@tsomic I see you only implemented a client-side search as you observed that the pagination is broken. I've resolved the bug with the pagination so pull the changes and make the search work with data from the server.

2024-05-05 19:33 UTC, KelvinGoboZap commented
@tsomic I noticed the pagination bug was introduced in your previous PR (https://github.com/slightlynerd/startupgraveyard.africa/pull/27) which was causing the `onPaginationChanged` handler to be called twice. I've resolved the bug so pagination should be working and you should be able to complete the search functionality.

Also, I notice a typo in the PR title. **earch** should be **search**.

2024-05-05 21:35 UTC, slightlynerd requested changes
@tsomic I noticed the pagination bug was introduced in your previous PR (https://github.com/slightlynerd/startupgraveyard.africa/pull/27) which was causing the `onPaginationChanged` handler to be called twice. I've resolved the bug so pagination should be working and you should be able to complete the search functionality.

Also, I notice a typo in the PR title. earch should be search.

2024-05-05 21:35 UTC, slightlynerd commented on package.json
> +    "@nuxtjs/sitemap": "^5.1.4",
@tsomic What's the reason for updating the packages? Just want to understand why this was done.

2024-05-05 21:35 UTC, slightlynerd commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
@tsomic I see you only implemented a client-side search as you observed that the pagination is broken. I've resolved the bug with the pagination so pull the changes and make the search work with data from the server.

2024-05-06 15:22 UTC, tsomic commented on package.json
> +    "@nuxtjs/sitemap": "^5.1.4",
Just to keep packages updated regularly, no urgent reason. Of course I can revert that commit if you prefer

2024-05-06 17:08 UTC, slightlynerd commented on package.json
> +    "@nuxtjs/sitemap": "^5.1.4",
@tsomic It's fine. Double-check to confirm existing functionality is not broken.

2024-05-06 21:05 UTC, tsomic commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
I have some problems trying to implement the search with data from the server. This is what I have been trying and I don't receive any data. 
![image](https://github.com/slightlynerd/startupgraveyard.africa/assets/60610467/cca42de4-8456-40df-ba1b-b9d11925241c)
https://stackoverflow.com/questions/46568142/google-firestore-query-on-substring-of-a-property-value-text-search

And even if it worked, I am pretty sure the search would be case-sensitive with the current configuration in Firebase. Do you have any ideas?

2024-05-07 15:12 UTC, slightlynerd commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
@tsomic I see the issue. We would have to use a temporary workaround and revert to client-side pagination and search. 

So basically what would be done is that all articles are fetched on the blog page. So pagination and search would be done client-side.

A `TODO:` comment should be added to the method for client-side pagination so it's refactored to server-side search and pagination at a later time.

Let me know if you can work on this or I can take it.

2024-05-07 19:00 UTC, tsomic commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
I added the comment and the client-side pagination and search.

I would prefer if you could work on the server-side implementation :)

2024-05-08 06:01 UTC, slightlynerd approved these changes

2024-05-08 06:02 UTC, slightlynerd commented on pages/blog/index.vue
> +    blog.title.toLowerCase().includes(searchTerm.value.toLowerCase())
@tsomic Yes, I'll work on the server-side implementation at a later time :)

2024-05-08 06:02 UTC, merged