Feature/card UI polish
slightlynerd/startupgraveyard.africa pull request #6
Opened 2023-12-13 13:00 UTC by brightiortsor

[Netlify Demo Link](https://cheery-dasik-1bf627.netlify.app)

This PR adds the following:

1. Modified the Startup card UI styles
2. Modified the grid layout to properly fit all screen sizes
3. Added a function to truncate the bio card description text (This was done to maintain a uniform card height on all screens)
4. Added a NotFound UI for when search result is empty

**FUTURE MODIFICATION SUGGESTIONS**

- Add a startup details page where to display all details of that startup (i.e all that is left of it anyways).
- Pagination as against the current infinite scroll
- Integrate a database to be able automate the process of adding graveyard startups. This will also help to reduce human errors as someone might want to delibrately add falsified information. 
- Very importantly, we need to add a VERY LARGE DISCLAIMER at the footer `e get why`.

![Screenshot (167)](https://github.com/slightlynerd/startupgraveyard.africa/assets/99312664/b570dc6d-1162-4600-b6e0-9b5d6ce4ccdf)
![Screenshot (168)](https://github.com/slightlynerd/startupgraveyard.africa/assets/99312664/af97cad8-9d47-4f2b-aaf0-94ba955e2e22)
![Screenshot (169)](https://github.com/slightlynerd/startupgraveyard.africa/assets/99312664/2296a672-a71b-4fe7-b072-c7af336771d8)
![Screenshot (170)](https://github.com/slightlynerd/startupgraveyard.africa/assets/99312664/16c72f36-55f5-4618-9064-e1b12ef72325)

2023-12-13 16:56 UTC, brightiortsor commented
@slightlynerd Hiii,
I have gone through your detailed justification for some of the initial modifications made and I agree with some actually.
Nonetheless, I have removed the bg color for both the card and not-found components as well as the truncated text func. These changes have been pushed accordingly. I hope we can bring on better ideas to improve the project going forward.

2023-12-13 18:58 UTC, slightlynerd commented
@brightiortsor Sure, I'll take a look at the PR and give feedback.

2023-12-14 10:10 UTC, slightlynerd requested changes

2023-12-14 10:10 UTC, slightlynerd commented on src/components/startup-bio.vue
> +  background: #f0eded;
@brightiortsor Move the hex (#f0eded) to src/styles/assets/styles/variables.scss, import the file and then use it.

```scss
// in variables.scss
$bg-shutdown: #f0eded;

// in startup-bio.vue
<style lang="scss" scoped>
@import '@/assets/styles/variables.scss';

...

// usage
.shutdown {
  background: $bg-shutdown;
  ...
}
</style>
```

2023-12-14 10:11 UTC, slightlynerd commented
@brightiortsor After making the changes, run `yarn lint` to fix lint errors.

2023-12-14 10:37 UTC, slightlynerd commented
@brightiortsor For subsequent commits, please read the contribution guide and follow the format for commit messages.

2023-12-29 06:27 UTC, closed without merging